
version: 2

models:
  - name: customers
    description: "Test for customers model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
      - name: first_name
        description: "The first name of the customer"
        tests:
          - not_null
      - name: last_name
        description: "The last name of the customer"
        data_tests:
          - not_null