# fichier de tests
version: 2

models:
  - name: dim_customers
    description: "Test for customers model"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        data_tests:
          - unique
      - name: first_name
        description: "The first name of the customer"
        data_tests:
          - not_null
      - name: last_name
        description: "The last name of the customer"
        data_tests:
          - not_null
          
  - name: stg_jaffle_shop_customers
    columns:
      - name: customer_id
        data_tests:
          - unique
          - not_null

  - name: stg_jaffle_shop_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_jaffle_shop_customers')
              field: customer_id
